export const apiEndpoints = {
  auth: {
    base: "/auth",
    login: "/auth/login/",
    logout: "/auth/logout/",
    refresh: "/auth/refresh/",
    me: "/auth/me/",
    changePassword: "/auth/change-password/",
  },
  facilities: {
    base: "/facilities",
    organizations: "/facilities/organizations/",
    facilityTypes: "/facilities/facility-types/",
    facilities: "/facilities/facilities/",
    departments: "/facilities/departments/",
    specialties: "/facilities/specialties/",
    facilitySpecialties: "/facilities/facility-specialties/",
    servicePointTypes: "/facilities/service-point-types/",
    servicePoints: "/facilities/service-points/",
    consultationRooms: "/facilities/consultation-rooms/",
    operatingHours: "/facilities/operating-hours/",
    scheduleExceptions: "/facilities/schedule-exceptions/",
    flowSettings: "/facilities/flow-settings/",
  },
  patients: { base: "/patients" },
  practitioners: { base: "/practitioners" },
  appointments: { base: "/scheduling/appointments" },
  checkins: { base: "/checkins" },
  queueing: { base: "/queueing" },
  intelligence: { base: "/intelligence" },
  notifications: { base: "/notifications" },
  reporting: {
    base: "/reporting",
    exports: "/reporting/exports/",
    analytics: {
      patientWaitingTime: "/reporting/analytics/patient-waiting-time/",
      appointmentUtilization: "/reporting/analytics/appointment-utilization/",
      doctorWorkload: "/reporting/analytics/doctor-workload/",
      dailyAttendance: "/reporting/analytics/daily-attendance/",
      predictionAccuracy: "/reporting/analytics/prediction-accuracy/",
    },
    dashboard: {
      overview: "/reporting/dashboard/overview/",
      appointments: "/reporting/dashboard/appointments/",
      queues: "/reporting/dashboard/queues/",
      checkins: "/reporting/dashboard/checkins/",
      practitioners: "/reporting/dashboard/practitioners/",
      intelligence: "/reporting/dashboard/intelligence/",
    },
  },
  audit: {
    base: "/audit",
    logs: "/audit/logs/",
    summary: "/audit/summary/",
    actors: "/audit/actors/",
    resources: "/audit/resources/",
  },
} as const;
