export const apiEndpoints = {
  auth: {
    base: "/auth",
    login: "/auth/login/",
    logout: "/auth/logout/",
    refresh: "/auth/refresh/",
    me: "/auth/me/",
    changePassword: "/auth/change-password/",
  },
  facilities: { base: "/facilities" },
  patients: { base: "/patients" },
  practitioners: { base: "/practitioners" },
  appointments: { base: "/scheduling/appointments" },
  checkins: { base: "/checkins" },
  queueing: { base: "/queueing" },
  intelligence: { base: "/intelligence" },
  notifications: { base: "/notifications" },
  reporting: {
    base: "/reporting",
    dashboard: {
      overview: "/reporting/dashboard/overview/",
      appointments: "/reporting/dashboard/appointments/",
      queues: "/reporting/dashboard/queues/",
      checkins: "/reporting/dashboard/checkins/",
      practitioners: "/reporting/dashboard/practitioners/",
      intelligence: "/reporting/dashboard/intelligence/",
    },
  },
  audit: { base: "/audit" },
} as const;
