export const permissionCodes = {
  reportingAnalyticsView: "reporting_analytics.view",
  schedulingAppointmentView: "scheduling_appointment.view",
  schedulingAppointmentCreate: "scheduling_appointment.create",
  schedulingAppointmentUpdate: "scheduling_appointment.update",
  schedulingAppointmentCancel: "scheduling_appointment.cancel",
  schedulingAppointmentReschedule: "scheduling_appointment.reschedule",
  schedulingAppointmentAssign: "scheduling_appointment.assign",
  queueingQueueView: "queueing_queue.view",
  queueingQueueManage: "queueing_queue.manage",
  queueingEntryView: "queueing_entry.view",
  queueingEntryCreate: "queueing_entry.create",
  queueingEntryCall: "queueing_entry.call",
  queueingEntrySkip: "queueing_entry.skip",
  queueingEntryStartService: "queueing_entry.start_service",
  queueingEntryCompleteService: "queueing_entry.complete_service",
  queueingEntryCancel: "queueing_entry.cancel",
  queueingEntryTransfer: "queueing_entry.transfer",
  queueingPriorityManage: "queueing_priority.manage",
  checkinsCheckinView: "checkins_checkin.view",
  patientsPatientView: "patients_patient.view",
  practitionersPractitionerView: "practitioners_practitioner.view",
  facilitiesFacilityView: "facilities_facility.view",
  intelligencePredictionView: "intelligence_prediction.view",
  notificationsNotificationView: "notifications_notification.view",
  reportingReportView: "reporting_report.view",
  auditLogView: "audit_log.view",
} as const;

export type AppPermissionCode =
  (typeof permissionCodes)[keyof typeof permissionCodes];
